In [1]:
import pandas as pd

## Import Processed dataset

In [2]:
# Load the original dataset
df = pd.read_csv('processed_data.csv')

## Randomly sampling 20 Data Points

In [3]:
# Randomly sample 20 data points
sampled_df = df.sample(n=20, random_state=86)

# Save the sampled dataset to a new file
sampled_df.to_csv('sample_dataset.csv', index=False)

## Importing the Model

In [4]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler, LabelEncoder
import joblib
from sklearn.metrics import accuracy_score, classification_report

In [5]:
# Step 1: Load the processed test data
test_data = pd.read_csv('sample_dataset.csv')

In [6]:
test_data

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner,selling_price_range
0,Ford Figo Diesel Titanium,2011,190000,110000,1,1,1,2,2
1,Fiat Grande Punto EVO 1.3 Dynamic,2014,325000,70000,1,1,1,1,2
2,Renault KWID RXT BSIV,2019,250000,27000,2,1,1,1,2
3,Maruti Swift Dzire VDI,2016,540000,80000,1,1,1,1,2
4,Mahindra Xylo D2 BS IV,2011,229999,110000,1,1,1,2,2
5,Renault KWID RXL,2016,229999,38000,2,1,1,1,2
6,Hyundai EON Era Plus,2012,200000,46000,2,1,1,1,2
7,Tata Venture EX,2012,110000,80000,1,1,1,1,2
8,Mahindra Scorpio 1.99 S10,2016,1025000,70000,1,1,1,1,3
9,Maruti Alto K10 VXI,2014,200000,80000,2,1,1,2,2
10,Hyundai EON 1.0 Era Plus,2018,100000,21302,2,1,1,1,1
11,Hyundai Santro Xing XO,2006,80000,110000,2,1,1,1,1
12,Hyundai Grand i10 1.2 Kappa Sportz BSIV,2019,500000,5000,2,1,1,1,2
13,Hyundai EON Era Plus Option,2014,265000,55000,2,2,1,1,2
14,Tata Indica Vista Aqua 1.4 TDI,2010,125000,81000,1,1,1,2,2
15,Maruti Swift Vdi BSIII,2008,120000,175000,1,1,1,2,2
16,Hyundai Elantra CRDi S,2012,625000,40000,1,1,1,1,2
17,Skoda Laura Ambiente 2.0 TDI CR MT,2012,385000,52000,1,2,1,1,2
18,Mahindra Xylo D4,2015,500000,50000,1,1,1,2,2
19,Hyundai EON LPG Magna Plus,2012,180000,90000,4,1,1,1,2

In [7]:
# Separate the features and labels
X_test = test_data[['year', 'km_driven', 'fuel', 'seller_type', 'transmission', 'owner']].values
y_test = test_data['selling_price_range'].values

In [8]:
# Step 2: Load the trained model, scaler, and label encoder
model = joblib.load('best_model.pkl')  # Load the pre-trained RandomForest model
scaler = joblib.load('scaler.pkl')     # Load the pre-fitted scaler
label_encoder = joblib.load('label_encoder.pkl')  # Load the pre-fitted label encoder

In [9]:
# Step 3: Feature Scaling 
# Ensure that the test dataset is scaled using the same scaler used during training
X_test_scaled = scaler.transform(X_test)

C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

In [10]:
# Step 4: Make Predictions
# Predict using the trained model
predictions_encoded = model.predict(X_test_scaled)

In [11]:
# Step 5: Decode predictions and the actual labels to readable format
predicted_labels = label_encoder.inverse_transform(predictions_encoded)
actual_labels = y_test

In [12]:
# Step 6: Compare predictions with actual labels
# Calculate accuracy and show classification report
accuracy = accuracy_score(actual_labels, predicted_labels)
report = classification_report(actual_labels, predicted_labels)

C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\metrics\_classification.py:1509: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [13]:
# Display Results
print(f"Accuracy of the model on the 20 data points: {accuracy * 100:.2f}%")
print("\nClassification Report:")
print(report)

Accuracy of the model on the 20 data points: 90.00%

Classification Report:
              precision    recall  f1-score   support

           1       1.00      0.50      0.67         2
           2       0.89      1.00      0.94        17
           3       0.00      0.00      0.00         1

    accuracy                           0.90        20
   macro avg       0.63      0.50      0.54        20
weighted avg       0.86      0.90      0.87        20

In [14]:
# Optional: Show a sample of predictions vs actual values
comparison_df = pd.DataFrame({
    'Actual': actual_labels,
    'Predicted': predicted_labels
})

print("\nSample Predictions vs Actual Labels:")
print(comparison_df.head(20))

Sample Predictions vs Actual Labels:
    Actual  Predicted
0        2          2
1        2          2
2        2          2
3        2          2
4        2          2
5        2          2
6        2          2
7        2          2
8        3          2
9        2          2
10       1          2
11       1          1
12       2          2
13       2          2
14       2          2
15       2          2
16       2          2
17       2          2
18       2          2
19       2          2